### ISSUE TITLE
Used assets dropped

### ISSUE THREAD

**Issue by Morphyum** [saltyhotdog/BattletechIssueTracker#13]
**Describe the problem**
The game has problems with its garbage collection:
1) It seems the game only uses about 4GB of ram before it unloads, not all available.
2) When the unload happens at mission loading it seems you run into a common unity problem, that breaks the game when you do loading and unloading at the same time. Assets that are needed in the mission get unloaded and the loading therefore never finishes.

This happens less or not at all in vanilla but since we use more assets in our mods it happens pretty commonly for us.

**Provide an example of your proposed solution**

https://answers.unity.com/questions/1112847/unloadunusedassets-causing-loss-of-used-assets.html
apparently a yield should fix that problem

```IEnumerator LoadNewAssetsRoutine ()
     {
         // Destroy your objects.
     
         yield return Resources.UnloadUnusedAssets();
     
         // Continue executing new actions and loading new objects.
     }```

**Comment by caardappel-hbs** [comment]
I realize I'm responding to something not marked HBS Ready, but this ticket is a little confused and I was already doing a pass.

1) Garbage bloat is its own problem that has been partially addressed in 1.1, but work does continue there. 
2) Our resources unload occurs at known intervals in order to prevent loss of assets. If a mod attempts to load something in an unexpected way, this could lead to loss of assets. Also, our call to unload unused is already a yield call, so I'm not quite sure what your suggestion means.

Mods should be requesting all assets before the level load begins, and loading them during EncounterBegin. There are some ways around this, of course.

Can you be more specific in describing the problem you're facing?

**Comment by Morphyum** [comment]
The problem we are facing is basically an endless load screen for the missions at unspecified moments and times. All above was just speculation and ideas, that's why its not HBS ready flagged. As far as i know we do not load anything at mission loading.
So if it is not because of asset drop then we are basically clueless why sometimes the missions don't load and why it happens more often with mods.

**Comment by LadyAlekto** [comment]
We dont load anything, one issue was found earlier has been my hidden inferno debuff to increase all heat weapon generation, which when called on a vehicle makes the hang up as soon as the contracts/reinforcements load

The others for this we are still tracking but its still true that too many assets cause issues when the game reaches 4 gigs with high GFX settings (the guys got some interesting data last night)

I would also like to to add that this can and does happen in an unmodded vanilla, just not as often

**Comment by caardappel-hbs** [comment]
10-4
We are improving load failure handling for an upcoming update. I expect that will resolve the majority of these issues.

**Comment by Morphyum** [comment]
Will close this ticket for now, since the issues have been greatly reduced by now.
